### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by robssanches**
Hi @mgibbs189 

I made some improvements in the plugin, among which stand out:

**1)** Creation of a "drag and drop fields area" in the Loop field, to make this field more intuitive.

drag_and_drop_area

**2)** Customization of the button colors and side borders of the loop fields, based on the color scheme defined by WP user.

default

midnight

ectoplasm

Also, I made some code improvements.

### CODE REVIEW

**Comment by mgibbs189** [comment]
@robssanches Thanks for the PR!

I love the Loop field UI improvements. Not a huge fan of the new constants though. Possible to update this PR to **only** include to Loop + color changes?

**Comment by robssanches** [comment]
> 
> 
> @robssanches Thanks for the PR!
> 
> I love the Loop field UI improvements. Not a huge fan of the new constants though. Possible to update this PR to **only** include to Loop + color changes?

Ok @mgibbs189 , I'll update the PR.

**Comment by robssanches** [comment]
Hi @mgibbs189, I updated the PR.

**Comment by robssanches** [comment]
@mgibbs189 

I updated the PR by removing the constants but keeping the changes in the Loop field and the colors of the UI Elements.

Need any further changes?

**Pull request closed without merging**
