### PR TITLE
Added functionality to autotype the label on variable-named loop fields

### PR DESCRIPTION
**Pull request by OutThisLife**
Just a simple UX update so that clients don't see a bunch of handlebars when going through loop fields.

### CODE REVIEW

**Comment by mgibbs189** [comment]
Thanks for contributing, @OutThisLife 

Can you confirm that this PR also works when creating a loop-within-a-loop?

**Comment by chrisvanpatten** [comment]
Just gave it a shot, and it doesn't work with nested loop fields. When the label updates in a nested loop row, it also updates the labels of the ancestor and any sibling rows.

Also: I wonder if it might be possible to update this so you can place a token anywhere inline? Right now you can only use this if your row label is _only_ a token, but it might be nice to allow mixed labels like `Photo: {photo_caption}`. Obviously a little trickier, but might make this more useful.

**Comment by chrisvanpatten** [comment]
Add'l note: would love to see support for `<select>` field values as well (presumably pulling from the selected option's text instead of the selected option's value attribute).

Otherwise, it looks pretty killer overall. Really appreciate the simplicity of the PR.

**Comment by chrisvanpatten** [comment]
Pinging @OutThisLife to see if you're interested in revisions to this PR :)

**Comment by mgibbs189** [comment]
Closing, per #348

**Pull request closed without merging**
