### PR TITLE
Optionally enable Select2 for select fields

### PR DESCRIPTION
**Pull request by chrisvanpatten**
This PR adds the ability to use Select2 for CFS select fields, in place of the standard browser `<select>` fields.

This is particularly useful for selects with lots of options, like a list of countries.

screen shot 2015-03-13 at 15 27 21

This does *not* work on selects within loop fields. I'm sure there's a way to do it, but it's beyond my limited JavaScript skillz.

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
(Worth adding that although it doesn't work on selects within loop fields, it does gracefully degrade back to a normal browser select. Still totally usable.)

**Comment by mgibbs189** [comment]
Thanks! I have 2 minor suggestions:

1. Before I merge, just wanted to make sure that this supports loop sub-fields
2. Possibility to only include Select2 assets if there are 1+ fields using it?

**Comment by chrisvanpatten** [comment]
1. I'm too stoopid to figure this out, although I tried :) Any suggestions? Happy to write the code, just need a push in the right direction.

2. I tried this, but it looks like input_head only examines the first field? Again, happy to code it, just need an idea on how to accomplish it!

**Comment by chrisvanpatten** [comment]
Also, FWIW, WordPress core is *theoretically* going to bundle Select2 with 4.2. (It was supposed to be in 4.1, but they pulled it). If it's going to be loaded in by default anyway (for tags/categories) would point 2 really matter? I'd be happy to wait until a bit after 4.2 to merge this, if it'd be dramatically simpler from a dev perspective.

**Comment by mgibbs189** [comment]
@chrisvanpatten sorry it's taken so long, been a busy few months!

I'm considering whether to add select2 or fSelect: https://github.com/mgibbs189/fSelect

**Comment by chrisvanpatten** [comment]
I tend to think if core is bundling something, it's better to use that solution... Buuuut... I would like the feature so much that it doesn't really matter :) 

Sorry I let my PR drop off too... work gets crazy and priorities shift, as I'm sure you know :)

**Comment by mgibbs189** [comment]
Closing for now, but I haven't forget about this :)

**Comment by chrisvanpatten** [comment]
I'm going to refresh this over the next few weeks, fwiw

**Pull request closed without merging**
