### PR TITLE
Add new 'image' field using WP Media Manager

### PR DESCRIPTION
**Pull request by ghost**
Needed an image field for a project, just sharing back :)

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
What's wrong with the file field?

**Comment by mgibbs189** [comment]
Agreed, thanks for submitting the PR but what don't you like about the `File` field type?

**Comment by jchristopher** [comment]
Looks like this just limits the available Media in the modal to images — maybe worth being an option for the `File` field in the future.

**Comment by chrisvanpatten** [comment]
Looks like that particular option can take the parameters 'image', 'audio', 'video', or 'file', plus any valid mimetype. Maybe it'd be worth supporting the basic four as a `<select>`, and have a filter to add additional options?

**Comment by mgibbs189** [comment]
@chrisvanpatten Sounds great, as long as there's also an "Any" option to preserve current functionality :)

**Comment by chrisvanpatten** [comment]
@mgibbs189 I believe (but will test) that the "file" option is functionally equivalent to "any".

**Comment by mgibbs189** [comment]
Closing. See #346

**Pull request closed without merging**
