### PR TITLE
Remove custom checkbox code

### PR DESCRIPTION
**Pull request by chrisvanpatten**
CFS currently supports checkboxes (the "true/false" field) through a JS toggle that masks a hidden input.

This method has a few issues:

+ Visually, it doesn't integrate with WordPress core
+ The graphic used is non-retina, and looks wonky on HiDPI displays
+ Most importantly, it's not accessible. When tabbing through a field group, the custom checkboxes are skipped

This PR replaces those fake checkboxes with a real/native checkbox.

The changes in this PR are 'backwards compatible', in the sense that existing true/false fields retain their values and are fully compatible with the new method. (Proof: 1. Install CFS from `master`; 2. create new field group with true/false fields; 3. save some values; 4. checkout `no_custom_checkboxes`, notice values persist; 5. flip back to master; notice values still persist).

I also think it's worth removing the "required" option for checkboxes (how can you require a true/false toggle?) but that's for another PR :smile:

### CODE REVIEW

**Comment by chrisvanpatten** [comment]
(Note: just re-pushed my feature branch… realised I was basing it from my select2 branch, instead of master. Fixed that!)

**Comment by chrisvanpatten** [comment]
@mgibbs189 Did you test it? I didn't experience any issues. Everything continued to save as normal.

**Comment by chrisvanpatten** [comment]
Scratch that. I had accounted for the possibility of returning NULL (which is what an empty checkbox does by default) in my code, but others may not. Revising now.

**Comment by mgibbs189** [comment]
@chrisvanpatten Yes.

When a checkbox is checked, it saves `1` to postmeta (good)
When unchecked, no value gets saved to postmeta (bad)

```php
var_dump( CFS()->get( 'my_truefalse', 123 ) );
// returns (int) 1 when checked
// returns NULL when unchecked
// it should return (int) 0 when unchecked

**Comment by chrisvanpatten** [comment]
Rebuilt this so it continues to use a hidden field, but now with a stock HTML checkbox fronting it (so JS is still required). Also wrapped the checkbox and message in a <label>, which allows you to toggle the checkbox state via label click (see [this](http://uxmovement.com/forms/why-your-checkboxes-need-to-have-label-tags/) and [this](http://ux.stackexchange.com/questions/35289/input-checkboxes-wrapped-inside-labels)).

**Comment by mgibbs189** [comment]
@chrisvanpatten Thanks, haven't tested the new code yet, but it looks good so far.

**Comment by chrisvanpatten** [comment]
Woot, thanks! Sorry I was confused before. :)

**Comment by mgibbs189** [comment]
Thanks @chrisvanpatten :+1:

**Pull request merged**
