### PR TITLE
Add documentation for Term field type

### PR DESCRIPTION
**Pull request by chrisvanpatten**
Goes with #365. Nothing more to add :)

### CODE REVIEW

**Comment by mgibbs189** [comment]
I like this new field type a lot

**Comment by chrisvanpatten** [comment]
I'll hold off on merging this until 2.6 goes live 🚀

**Comment by chrisvanpatten** [comment]
This should probably be merged in; looks like the term field is live (not sure how I missed that!)

**Comment by mgibbs189** [comment]
Roger that, thanks @chrisvanpatten

**Pull request merged**
