### PR TITLE
resolve a fatal error on pre_save on v2.6.6 -

### PR DESCRIPTION
**Pull request by tabakman**
on field_html.php removed (int) from $field->weight to solve a type issue.
sanitation for this field will have to wait for another day :)

### CODE REVIEW

**Comment by mgibbs189** [comment]
What's the exact error message you were getting?

**Comment by tabakman** [comment]
@mgibbs189 under settings > custom field suite, adding or editing custom fields to a field group is currently broken on 2.6.6. when adding two or more fields, you will get a 'PHP Fatal error: Uncaught Error: Call to a member function pre_save_field() on null in [...]/wp-content/plugins/custom-field-suite/includes/field_group.php:199 [...]'

**Comment by lemonhead** [comment]
I have the exact same issue.

**Comment by mgibbs189** [comment]
Fair enough, merged. Thanks @tabakman

**Comment by lemonhead** [comment]
It works. Many thanks for instant fixing.

**Pull request merged**
