### PR TITLE
(Re-)introduce a select2 select field option

### PR DESCRIPTION
**Pull request by chrisvanpatten**
I've rebuilt my previous select2 pull request (#256). It's now fully compatible with loop fields and only loads the select2 code if a field on the current page uses select2.

### CODE REVIEW

**Comment by mgibbs189** [comment]
:+1:

**Comment by chrisvanpatten** [comment]
Woot! Let me know if there's anything you need for a merge.

**Comment by chrisvanpatten** [comment]
FYI that last commit just updates the branch to be synchronous with `master`.

**Comment by chrisvanpatten** [comment]
Just wanted to see if anything was needed for this to go into master :) Thanks!

**Comment by mgibbs189** [comment]
@chrisvanpatten Not at this point, thanks though.

This is one of those changes that needs a lot of testing (time permitting). select2 is a really popular library (with both v3 and v4 out now), and I'll need to make absolutely sure these changes won't conflict with other plugins using select2.

**Comment by mgibbs189** [comment]
Sorry for the delay!

**Comment by chrisvanpatten** [comment]
:rocket: Thanks Matt!

**Pull request merged**
